name: textf_benchmark
description: A new Flutter project to showcase Textf library with flex_color_scheme
publish_to: "none"
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.13.0
  flutter: ">=3.47.0"

dependencies:
  flex_color_scheme: ^9.0.0
  flutter:
    sdk: flutter
  textf: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^11.0.0

flutter:
  uses-material-design: true
