name: textf
description: >
  Inline Markdown-like formatting for Flutter - as drop-in replacements for `Text` and `TextEditingController`.
  Bold, italic, code, [URL links](.), highlights, super/subscript.
version: 1.2.2
homepage: https://github.com/PhilippHGerber/textf
repository: https://github.com/PhilippHGerber/textf
issue_tracker: https://github.com/PhilippHGerber/textf/issues

environment:
  sdk: ^3.5.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

topics:
  - text
  - markdown
  - formatting
  - text-editing
  - rich-text

screenshots:
  - description: "Textf Logo"
    path: pub/textf.webp
  - description: "Basic Formatting"
    path: pub/textf_basic.webp
  - description: "Superscript & Subscript"
    path: pub/textf_script.webp
  - description: "Textf Links"
    path: pub/textf_links.webp
  - description: "Placeholders"
    path: pub/textf_placeholders.webp
  - description: "TextField with TextfEditingController"
    path: pub/textf_editing_controller.webp
