import 'package:flutter/material.dart';

import '../styling/textf_style_resolver.dart';
import 'format_stack_entry.dart';
import 'textf_token.dart';

/// Encapsulates the state of the parser during the text processing.
///
/// This class maintains all the necessary variables during the parsing process,
/// including the input tokens, the base text style, matching marker pairs,
/// the current formatting state, and the style resolver. It also provides
/// methods for common state operations like flushing accumulated text
/// with the currently applied formatting.
class ParserState {
  /// Creates a new parser state.
  ///
  /// Requires the original source text, the token list, the base text style,
  /// the map of valid matching marker pairs, and the style resolver.
  ParserState({
    required this.tokens,
    required this.baseStyle,
    required this.matchingPairs,
    required this.styleResolver,
    this.textScaler,
    this.placeholders,
  });

  /// The list of tokens generated by the tokenizer for the input text.
  final List<TextfToken> tokens;

  /// The base text style provided.
  final TextStyle baseStyle;

  /// A map of matching marker pairs.
  final Map<int, int> matchingPairs;

  /// The style resolver instance.
  final TextfStyleResolver styleResolver;

  /// The list where generated InlineSpans are collected.
  final List<InlineSpan> spans = [];

  /// A buffer for accumulating plain text content between formatting markers.
  final StringBuffer textBuffer = StringBuffer();

  /// A stack tracking the currently active formatting markers.
  final List<FormatStackEntry> _formatStack = [];

  /// An optional `TextScaler` for scaling the text.
  final TextScaler? textScaler;

  /// Optional map of inline spans to substitute into placeholders.
  /// Keys correspond to the text inside braces (e.g., "icon" matches "{icon}").
  final Map<String, InlineSpan>? placeholders;

  /// Pushes a format onto the stack for the opening marker at [tokenIndex].
  ///
  /// Looks up the matching closing index from [matchingPairs] and the marker
  /// token from [tokens]. Computes the resolved style by applying the marker
  /// on top of [currentStyle] and caches it in the new stack entry.
  void pushFormat(int tokenIndex) {
    final TextfToken token = tokens[tokenIndex];
    assert(token is FormatMarkerToken, 'pushFormat called with non-marker token');
    if (token is! FormatMarkerToken) return;

    final int? matchingIndex = matchingPairs[tokenIndex];
    assert(matchingIndex != null, 'pushFormat called without a matching pair');
    if (matchingIndex == null) return;

    final TextStyle resolved = styleResolver.resolveStyle(token.markerType, currentStyle());
    _formatStack.add(
      FormatStackEntry(
        index: tokenIndex,
        matchingIndex: matchingIndex,
        type: token.markerType,
        resolvedStyle: resolved,
      ),
    );
  }

  /// Pops the top entry for the closing marker at [closingTokenIndex].
  void popFormat(int closingTokenIndex) {
    assert(
      _formatStack.isNotEmpty && _formatStack.last.matchingIndex == closingTokenIndex,
      'Closing marker does not match stack top - nesting validation failed',
    );
    if (_formatStack.isEmpty || _formatStack.last.matchingIndex != closingTokenIndex) {
      throw StateError('Closing marker does not match stack top');
    }

    _formatStack.removeLast();
  }

  /// Resolves the current style based on the format stack and base style.
  ///
  /// O(1): returns the pre-computed [FormatStackEntry.resolvedStyle] from the
  /// stack top, or [baseStyle] when the stack is empty.
  TextStyle currentStyle() {
    if (_formatStack.isEmpty) return baseStyle;

    return _formatStack.last.resolvedStyle;
  }

  /// Flushes the accumulated `textBuffer` as a `TextSpan` with the current formatting applied.
  ///
  /// Creates a `TextSpan` (or script span) from [currentStyle] and the buffered
  /// text, appends it to [spans], then clears [textBuffer].
  void flushText() {
    if (textBuffer.isEmpty) return;

    final String text = textBuffer.toString();
    final resolvedStyle = currentStyle();

    final bool isSuperscript = _formatStack.any((e) => e.type == FormatMarkerType.superscript);
    final bool isSubscript = _formatStack.any((e) => e.type == FormatMarkerType.subscript);

    if (isSuperscript || isSubscript) {
      spans.add(
        styleResolver.createScriptSpan(
          text: text,
          style: resolvedStyle,
          isSuperscript: isSuperscript,
        ),
      );
    } else {
      spans.add(TextSpan(text: text, style: resolvedStyle));
    }

    textBuffer.clear();
  }
}
