name: textf_editing_controller
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  textf: ^1.1.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/img/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf
        - asset: assets/fonts/RobotoMono-Italic-VariableFont_wght.ttf
          style: italic
